DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), AUTHOR_ID INT, GENRE_ID INT,
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
  FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID));

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(ID INT PRIMARY KEY AUTO_INCREMENT, BOOK_ID INT, COMMENT VARCHAR(255),
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID));
